Add a global killswitch
pytorch/dr-ci pull request #5
Opened 2020-10-13 21:58 UTC by bigfootjon

We can merge this when we're ready to tentatively launch the FB-internal version of Dr. CI.

If we end up needing to re-enable the AWS version we can either revert this PR or change `isPostingEnabledGlobally` to `True`

Test plan:
???
It compiled?

2020-10-13 22:07 UTC, yns88 requested changes
Per DMs, we should only killswitch on [creating new comments](https://github.com/pytorch/dr-ci/blob/cda06bcfaf84ef0644366d0084cd9bd34f04d099/app/fetcher/src/StatusUpdate.hs#L666), and continue to update existing comments made by this app.

2020-10-13 22:39 UTC, bigfootjon commented
Per more DMs, we can killswitch updating comments as well. The best place to do this is [wipeCommentForUpdatedPr](https://github.com/pytorch/dr-ci/blob/cda06bcfaf84ef0644366d0084cd9bd34f04d099/app/fetcher/src/StatusUpdate.hs#L852)

2020-11-30 19:07 UTC, yns88 requested changes
Can you also killswitch the creation of comments? https://github.com/pytorch/dr-ci/blob/cda06bcfaf84ef0644366d0084cd9bd34f04d099/app/fetcher/src/StatusUpdate.hs#L741

2020-12-02 18:07 UTC, yns88 approved these changes

2020-12-10 15:04 UTC, merged